-- Create Database and Schemas
CREATE OR REPLACE DATABASE SNOWPARK_DB;
USE DATABASE SNOWPARK_DB;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRANSFORMED;
CREATE OR REPLACE SCHEMA CURATED;

-- Use the Staging Schema
USE SCHEMA SNOWPARK_DB.STAGING;

-- Create Staging Tables
CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.INDIA_SALES_ORDER_CP
(
    ORDER_ID VARCHAR(1000),
    CUSTOMER_NAME VARCHAR(1000),
    MOBILE_MODEL VARCHAR(1000),
    QUANTITY VARCHAR(1000),
    PRICE_PER_UNIT VARCHAR(1000),
    TOTAL_PRICE VARCHAR(1000),
    PROMOTION_CODE VARCHAR(1000),
    ORDER_AMOUNT VARCHAR(1000),
    GST VARCHAR(1000),
    ORDER_DATE VARCHAR(1000),
    PAYMENT_STATUS VARCHAR(1000),
    SHIPPING_STATUS VARCHAR(1000),
    PAYMENT_METHOD VARCHAR(1000),
    PAYMENT_PROVIDER VARCHAR(1000),
    MOBILE VARCHAR(1000),
    DELIVERY_ADDRESS VARCHAR(1000)
);

CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.USA_SALES_ORDER_CP
(
    SOURCE_DATA VARIANT
);

CREATE OR REPLACE TABLE SNOWPARK_DB.STAGING.FRANCE_SALES_ORDER_CP
(
    SOURCE_DATA VARIANT
);

-- Create Storage Integration (replace placeholders with your own AWS info)
CREATE OR REPLACE STORAGE INTEGRATION SNOWPARK_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '<AWS_IAM_ROLE_ARN>'
STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_S3_BUCKET_NAME>/');

-- Check Integration details
DESC INTEGRATION SNOWPARK_INT;

-- Create External Stage
CREATE OR REPLACE STAGE SNOWPARK_DB.STAGING.SNOWPARK_STAGE
STORAGE_INTEGRATION = SNOWPARK_INT
URL = 's3://<YOUR_S3_BUCKET_NAME>/';

-- Validate Stage (lists files in the stage)
-- ls @SNOWPARK_DB.STAGING.SNOWPARK_STAGE;